### ISSUE TITLE
vpnkit.exe eating my RAM

### ISSUE THREAD

**Issue by soar** [moby/vpnkit#371]
This happened after updating to 18.* branch. At this moment I have `18.03.0-ce-rc4-win57 (16511)` build and my `vpnkit.exe` steals gigabytes of RAM in 2-3 hours with 2 containers running.

Like this:

![2018-03-25 18-00-20](https://user-images.githubusercontent.com/30570/37876565-df48c5e2-3056-11e8-8588-7991868e47e0.png)

Or even like this:

![2018-03-24 16-10-41](https://user-images.githubusercontent.com/30570/37876568-e907caf6-3056-11e8-88aa-1c781fbde09f.png)

I think it should never consume about 8 GBs of my RAM.

**Comment by soar** [comment]
Better and better...

![2018-03-25 18-38-54](https://user-images.githubusercontent.com/30570/37876889-ebb4fc56-305b-11e8-8235-edca1e9802ee.png)

**Comment by bartoncasey** [comment]
I have this issue as well. vpnkit.exe claims memory in proportion to the amount of network activity into and out of the docker containers, and never releases it.

**Comment by bartoncasey** [comment]
1 day later it's sitting at 1.2G, from light traffic.

**Comment by laarmen** [comment]
We are several here at work having this exact issue.

**Comment by djs55** [comment]
Thanks for your reports.

In order to make progress with this issue I need some reproduction steps. Could you provide a `docker-compose.yml` (or similar) and instructions to reproduce the problem?

**Comment by laarmen** [comment]
After trying a bit, it seems opening an HTTPS connection to a server on our internal network triggers the bug. The same doesn't apply to external, public servers (i.e. docker.com) nor other Docker instances.

**Comment by djs55** [comment]
@laarmen thanks for the update. Could you trigger the bug and then upload a diagnostic report? I'd like to take a look at the logs.

**Comment by laarmen** [comment]
See https://github.com/laarmen/VpnKitPoC for the code. How can I do the diagnostic report thing?

**Comment by djs55** [comment]
On Windows there should be a whale-shaped icon in the system tray. After
right clicking on it there should be a menu item called something like
"Diagnose and Feedback". Clicking on this should take you to a dialog where
diagnostics are uploaded and assigned a unique id. If you quote the id in
the ticket then I can download the logs and take a look.

(Sorry I couldn't give more precise instructions but I don't have a Windows
machine to hand)

**Comment by laarmen** [comment]
I'm not entirely sure this was an instance of the bug as I was still under the 300MB bar of RAM used by vpnkit, but it was consistently climbing. I'll upload another report if I get to the "eat-my-RAM" levels later.

ID: 5E3BFA7A-FF8F-4077-8583-773FF79518CC/2018-03-30_18-33-45

**Comment by laarmen** [comment]
In case that's useful, I just stopped all the docker containers on my workstation, waited a few minutes, and the vpnkit process sits at 700MB. I uploaded a second diagnosis, see 5E3BFA7A-FF8F-4077-8583-773FF79518CC/2018-03-30_19-09-21

**Comment by laarmen** [comment]
This time on my home computer and network, same code except that the target (on local network) is using plain http (no SSL), the memory grew to 1.5GB.

ID: D25DA2F3-2F67-42BA-A292-78A39BCBAEC4/2018-03-30_20-34-58

**Comment by cnuernber** [comment]
We are having same issue.  This is happening to us in under one day (although we are using an app that generates a lot of network traffic).  So we currently have to bounce docker once per day.

![pastedimage](https://user-images.githubusercontent.com/40426/38169259-cbc3107e-3522-11e8-8c45-962696f8654e.png)

**Comment by krukid** [comment]
Same thing for me - I'm running a single Node.js process that downloads remote files over HTTP (text and binary) - some 25-30K files, ~1GB in volume. VPNKit process consumes all available RAM within hours (I've had it consume up to 9GB of RAM, even though the overall limit for Docker itself is 2GB).

**Comment by bazzilic** [comment]
Same here. Win 10 x64, docker version:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:21:06 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

vpnkit.exe currently at 7GB, constantly climbing:

![image](https://user-images.githubusercontent.com/1805832/38296922-76750108-3825-11e8-9a1b-1ad8febfa8d7.png)

0 containers running. Uploaded a diagnostic, id: `29542F91-6441-4210-934F-DB948F4EF0EF/2018-04-04_16-34-22`

**Comment by dsmaher** [comment]
Here's a simple `docker-compose.yaml` that can reproduce the issue.  If you watch memory usage on `vpnkit.exe` when this is running, it climbs bu almost 1M every time the `wget` runs.

```version: '3'
services:
  eat-memory:
    image: busybox
    entrypoint: sh
    command:
      - -c
      - |
        while true; do
          echo Getting docker.com...
          wget -qO/dev/null https://www.docker.com
          sleep 5
        done```

**Comment by bazzilic** [comment]
In my case it climbs even if there’s no activity related to docker at all. At least, nothing explicit.

**Comment by logich** [comment]
I have this same issue occurring with 3 containers that are doing a large amount of WAN activity. If left to run over a week this will consume all the available RAM and leave the system in a unstable state. My only work around is restarting docker regularly.

**Comment by tcederquist** [comment]
Cross link forum entry of many folks with the same vpnkit memory issue: https://forums.docker.com/t/vpnkit-uses-all-free-memory/48558/12  For me I suspect the behavior appeared with the 16762 build - never noticed this before but wasn't looking until it exhausted my memory for one simple nginx container.

**Comment by arnie311** [comment]
I am having the same issue. 
Docker Version 18.03.0-ce-win59 (16762)
Windows Server 2016 with 32GB of Memory
Limit docker to 10gb of memory and vpnkit.exe uses up to 16GB in 24 hours.
![snag_289fdd8a](https://user-images.githubusercontent.com/10731453/39071290-1e5d72aa-44ac-11e8-9784-67592608ef02.png)
It either crashes or I have to restart Docker

**Comment by jtownley** [comment]
I hate to post a me too but, me too:
Docker Version 18.03.0-ce-mac60 (23751)
Channel: stable
6ddfc0f1d3
OSX 10.11.6   (16GB Ram)
Running one talkative (http outgoing requests only) app via docker compose

**Comment by tsasioglu** [comment]
We've rolled back to 17.12.0-ce-win47 2018-01-12 and are no longer seeing this issue.

**Comment by bartoncasey** [comment]
` .\vpnkit.exe --debug --ethernet foo` will spit out a git sha:
```
PS C:\Program Files\Docker\Docker\Resources> .\vpnkit.exe --debug --ethernet xxx
vpnkit.exe: [INFO] Setting handler to ignore all SIGPIPE signals
vpnkit.exe: [INFO] Version is eb91fd8319abdfcaf87a1839e46b7ce0577b68fc
...
```
That's for the current Version 18.04.0-ce-rc2-win61 (17070). It corresponds to the most recent commit here. 

@tsasioglu What does your 17.12.0-ce-win47 report?

**Comment by imarotte** [comment]
Is there an easy way to roll back to 17.12.0-ce-win? As it is, 18 is completely unusable for me. I have to restart every 90 min because vpnkit uses +90% of my memory

**Comment by apm963** [comment]
@imarotte Yes, you can download 17.12.0-ce-win47 here: https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17120-ce-win47-2018-01-12. I rolled back two of our staff to that version yesterday. The steps I tool were:
*  Uninstall the existing version of Docker for Windows (this removes the VM image - you might want to back it up from the default location of `C:\Users\Public\Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx` and restore after the reinstall)
*  Restart Windows (might be optional)
*  Run the installer from the link provided
    *  I had to restart Windows again because the `docker` cmdlet wasn't working in Powershell
*  Re-add to swarm if appl.

That is the simplest way, although you may end up losing your containers if the VM image is incompatible.

**Comment by ericblade** [comment]
Thanks @imarotte for linking the issue from the docker tracker.  When I've been watching mine, it's been rapidly climbing to around 1GB, on a 4GB machine (lol) then backing off, then reclimbing.  There's a GIF watching memory usage in Task Man attached to the link in docker/for-win 1932.  I have had the machine go completely unresponsive twice in the last week, though, which is highly abnormal, and could be due to disk thrashing caused by memory exhaustion.  I haven't *yet* bumped my Docker version back, because I was hoping that this would get fixed rapidly, and I have enough problems with going *forward* through Docker versions, that I don't want to see what kind of Hellgate I can open by trying to go backwards.  It definitely occurred when upgrading to 18.03, though. I don't know what version I had before, specifically, as I hadn't been paying attention, because I didn't have problems :-)

I do run a nginx in docker that redirects traffic to a few other containers as well as services that run natively on the bare metal.  As an aside, I do intend to put more RAM in the box, but so far, it hasn't really presented a problem to me, except that I can't force a docker restart without logging out or rebooting first.

**Comment by ericblade** [comment]
Just picked up the update to 18.03.1, and after about 15 minutes of runtime, vpnkit is hanging out at 13.7 to 14.0MB . . . so.. i'll keep an eye on it, but it seems to be fixed?

**Comment by ericblade** [comment]
![image](https://user-images.githubusercontent.com/1451847/39539883-028623da-4e0f-11e8-8826-b6ae3d63af48.png)

18.03.1 on Win 10 1803 after about 12 hours

**Comment by yixunx** [comment]
I'm using Docker for Mac 18.03.1-ce-mac65 (24312) and hit the same issue after running vpnkit for ~5 hours:
![image](https://user-images.githubusercontent.com/12816762/39551845-b8417f74-4e34-11e8-883d-5012dae45d53.png)

Docker version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

Docker info:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 28
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.71GiB
Name: linuxkit-025000000001
ID: PWN5:BICM:VGBT:GP5H:DCER:EUBH:V2NB:JQSR:VU52:PNWG:XNQZ:VXPV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 54
 System Time: 2018-05-02T22:08:32.337136965Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Downgrading to 17.12 seems to fix it. Happy to provide any diagnostics.

**Comment by Parktimo** [comment]
I uploaded a diagnostic:  FB03AA8B-F86C-4E7A-87B8-3A05EA2E2E0D/2018-05-08_10-54-58

vpnkit was using 22, almost 23 GB of memory after running over the weekend.

**Comment by ericblade** [comment]
saw someone was asking for docker-compose.. 

````
version: '3'
services:
  mail:
    restart: always
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: myemaildomain.com
    container_name: mail
    # network_mode: "host"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "110:110"
      - "995:995"
      - "4190:4190"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./mail/config:/tmp/docker-mailserver/
      - ./mail/config/sasl_passwd:/etc/postfix/sasl_passwd
      - ./mail/config/sasl_passwd.db:/etc/postfix/sasl_passwd.db
      - ./mail/config/eric.dovecot.sieve:/var/mail/myemaildomain.com/eric/.dovecot.sieve
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_POP3=1
      - ENABLE_MANAGESIEVE=1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  mysql4:
    build: mysql4/mysql4
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - d:\www:/usr/share/nginx/html
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=myhostname.com
      - NGINX_PORT=80

  # let's build a phpbb
  mariadb:
    restart: always
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'd:\docker\phpbb\mariadb:/bitnami'
    networks:
      - phpbb
  phpbb:
    restart: always
    image: 'bitnami/phpbb:latest'
    depends_on:
      - mariadb
    ports:
      - '9999:80'
      - '4443:443'
    volumes:
      - 'd:\docker\phpbb\phpbb2:/bitnami'
      - 'd:\docker\phpbb\ext:/opt/bitnami/phpbb/ext'
      - 'd:\docker\phpbb\styles:/opt/bitnami/phpbb/styles'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VIRTUAL_HOST=myhostname.com
      - LETSENCRYPT_HOST=myhostname.com
      - LETSENCRYPT_EMAIL=emailaddr@hostname.host
    networks:
      - phpbb

networks:
  phpbb:

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  certs:
    driver: local
  certs-data:
    driver: local
````
